erp_intelligence:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      dataset: staging          # dev → dataset 'staging'
      location: asia-south1
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      dataset: marts            # prod → dataset 'marts'
      location: asia-south1
      threads: 8
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
